import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const grotesk = localFont({
  src: [
    {
      path: './fonts/Grotesk-02Mince.woff',
      weight: '100',
    },
    {
      path: './fonts/Grotesk-03Regular.woff',
      weight: '400',
    },
    {
      path: './fonts/Grotesk-04Gras.woff',
      weight: '900',
    },
  ],
  variable: '--font-grotesk',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
